### ISSUE TITLE
Grunt Deploy adding node modules causing conflict with master

### ISSUE THREAD

**Issue by deeforte** [ga-wdi-boston/browser-template#102]
Opening issue with browser template to be investigated.   I have a workaround but we want to make sure the issue is documented.
While running the grunt deploy during script line 16 -
command: 'test -z "$(git status --porcelain)"  || (git status && false)'
is adding node modules to gh-pages branch.   When we get to the last command -
git checkout master - grunt deploy aborts because of conflict with master branch.   Danny helped with a workaround to rm -rf node_modules/ and then I'm able to checkout to master and the deploy finishes.

**Comment by Jcornmanhomonoff** [comment]
@gaand says the most likely reason for this is that node_modules were added to the git repository.
