### ISSUE TITLE
Add `grunt deploy` task

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/browser-template#24]
-   [ ] `grunt build` to `dist` directory (directory tracked in #21; `dist` is untracked and useful for local testing)
-   [ ] `grunt deploy` copies `dist` to `tmp` (`tmp` must be untracked)
  -   [ ] `git checkout gh-pages`
  -   [ ] `grunt clean` (`git clean` everything; not yet written)
  -   [ ] copy `tmp` to current working directory
  -   [ ] add all and commit with a release number
  -   [ ] git checkout last branch

**Comment by gaand** [comment]
This 9bcfc994c1710f42336f6d87c78435cd00dc6c31 may close this issue.

**Comment by jrhorn424** [comment]
I agree. Not what I had outlined above, but it does the job I was attempting to describe with the checklist! Right behavior, different implementation and that's A-Ok with me!

![](https://media.giphy.com/media/bqrG9EUt9vS4U/giphy.gif)
