### ISSUE TITLE
Use `node-noop` to stop processing of SVGs and fonts?

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/browser-template#25]
Developers don't seem to be using glyphicons that much. Does it make sense to send SVGs and fonts to the bitbucket instead of building output?

**Comment by gaand** [comment]
I think as we continue to improve we'll get them to use glyphicons more.  Words for buttons should be relegated to tooltips. :-P.

**Comment by jrhorn424** [comment]
I'm closing this. Feel free to reopen if anyone wants to discuss.
