### ISSUE TITLE
Add jpg and png files to webpack

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/browser-template#38]
Where webpack tests for ttf | eot | svg files, it doesn't look for other image files. Add jpg | png after  svg to include these file types when grunt serve/build is run.

**Comment by gaand** [comment]
Should we encourage serving these sort of files from AWS S3 or similar?

**Comment by berziiii** [comment]
Commit 56471dd9a180c0d0476518e4e2c0d0bad70d7af3 fixes this issue. Of course, welcoming addition Webpack improvements. Leaving open for now due to additional suggestions by @gaand.

**Comment by jrhorn424** [comment]
@gaand Yes, it should be encouraged, but maybe not during the first project?

**Comment by gaand** [comment]
I think this 9bcfc994c1710f42336f6d87c78435cd00dc6c31 may close this issue.  We may need another for the "server from AWS" point.

**Comment by jrhorn424** [comment]
> We may need another for the "server from AWS" point

Agreed. This is closeable.
