### ISSUE TITLE
.gitignore has carriage returns

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/browser-template#46]
Please remove those, thanks.

**Comment by jrhorn424** [comment]
Carriage returns are needed for Windows ignores. Don't blame me.

We can remove Windows ignores if you like.

**Comment by gaand** [comment]
I'd be surprised if git required carriage returns on every line of the .gitignore file (which I believe prompted this).

**Comment by gaand** [comment]
Yuckity yuck yuck.  the .gitignore in this repo isn't the same as the one in talk-template, the difference is carriage returns in this one.

**Comment by gaand** [comment]
That plus the webpack specifics.  If we're going to have different .gitignores, then why strive for one comprehensive one?

Or put the webpack specifics in the version used everywhere else?

**Comment by jrhorn424** [comment]
> Or put the webpack specifics in the version used everywhere else?

I agree.
