### ISSUE TITLE
Developer's JavaScript ends up in `dependencies.js`

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/browser-template#61]
Formally `vendor.bundle.js`

This seems incorrect.  If you haven't added any new npm modules, I think that should build once and remain unchanged.

**Comment by gaand** [comment]
Fixed in 9bcfc994c1710f42336f6d87c78435cd00dc6c31

**Comment by jrhorn424** [comment]
Here: https://github.com/ga-wdi-boston/browser-template/commit/9bcfc994c1710f42336f6d87c78435cd00dc6c31#diff-4a90538dbcd6ace7476c0c39feddb6ceR23

I agree, good to close.
