### ISSUE TITLE
Add `.nojekyll` file to root of repository.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/browser-template#62]
Re: GitHub Pages seems to be excluding files with "vendor" in the name

Hey Antony,

Thanks for reaching out! We've recently updated to Jekyll v3.3, which ignores vendored files by default. To include your vendored files in your build, you'll have to add this to your `_config.yml` file:

```
include:
  - vendor
```

Alternatively, if you're not using Jekyll, you can add a `.nojekyll` to the root of your repository to disable Jekyll completely during your site build, so those files won't be ignored.

Could you give that a try and let me know if that works?

Cheers,
Antonio
GitHub Support

Deploying a webpack built app with "vendor.bundle.js" or "vendor.js" stopped working sometime yesterday.

Renaming the file to a name without "vendor", I tried "bob.js" and "dependencies.js", worked fine.

**Comment by gaand** [comment]
This also means we should revert the updates to the deployment guide and this repository meant to deal with this issue.

**Comment by gaand** [comment]
Handle in deploy task added in 9bcfc994c1710f42336f6d87c78435cd00dc6c31

**Comment by jrhorn424** [comment]
@gaand This is close-able? We're happy with the names of the bundles?
