### ISSUE TITLE
Delete gh pages branch

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/browser-template#74]
I accidentally created a gh-pages branch and does not have permission to remove it

Was playing with Antony's grunt deploy script and forgot to fork.

**Comment by jrhorn424** [comment]
I took care of it.

**Comment by BenGitsCode** [comment]
Thank you </shame>

-- 
*Ben Adamski | Developer in Residence*
General Assembly Boston | 125 Summer Street, Boston MA 02210
ben.adamski@generalassemb.ly | xxx-xxx-xxxx |

On December 16, 2016 at 12:39:19 PM, Jeffrey Horn (notifications@github.com)
wrote:

I took care of it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ga-wdi-boston/browser-template/issues/74#issuecomment-267651336>,
or mute the thread
