### ISSUE TITLE
stupid trailing comma

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/browser-template#87]
Fixed in most recent PR https://github.com/ga-wdi-boston/browser-template/pull/86, but still a problem now.

**Comment by payne-chris-r** [comment]
Resolved with https://github.com/ga-wdi-boston/browser-template/pull/86/commits/88aa72cb2847255f371751835739564c850cad19

**Comment by gaand** [comment]
@payne-chris-r Any reason you didn't close this with the commit comment?
