### ISSUE TITLE
No jscs stuff?

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/browser-template#88]
`master` still has `jscs` and some `jshint` stuff in package.json file. I think we need to remove those!

**Comment by jrhorn424** [comment]
>  I think we need to remove those!

I believe you are correct.

**Comment by gaand** [comment]
They have been removed from a pull on node-template.

ga-wdi-boston/node-template/pull/29

**Comment by payne-chris-r** [comment]
Resolved by b6bd85 https://github.com/ga-wdi-boston/node-template/pull/29/commits/b6bd857c990804e122a430ccc97323950770d583
