### ISSUE TITLE
styles/scss file incompatible 

### ISSUE THREAD

**Issue by logicmyth** [ga-wdi-boston/browser-template#94]
My issue with the browser template is that the scss file (within styles folder) is not effecting the html file.
I changed the body of the html file but not the head.
i am accessing the div that started the issue with the class selector in scss and the class tag in html.
I had an issue with my first repo bc the console said it couldn’t find the scss file but I trashed that repo and now the errors I get from the console are 404s for vendor.js and application.js

I know I don't have style in the everyday sense, but I should have a working stylesheet.

**Comment by gaand** [comment]
This seems unlikely if you are using the browser template correctly as it has worked for more than 100 other developers.

**Comment by logicmyth** [comment]
i agree completely. i downloaded, unzipped, and copied into the git-backed folder. is there some of me unconsciously meddling with the git init or setting up git? i kept the setup as minimal as possible and modified the html body and scss file only in this new repo.

**Comment by jrhorn424** [comment]
@logicmyth What's the URL you see when the style isn't working?

**Comment by logicmyth** [comment]
My best answer is I'm not getting a consoled error when the style isn't working, just 404s for app.js and vendor.js
the url for the mongoose port is: `http://10.1.4.175:8080/theVoid/browser-template-master/`
And the scss file has the template requirement urls for bootstrap.

**Comment by jrhorn424** [comment]
What do you mean mongoose?

**Comment by logicmyth** [comment]
Berzi showed me an alternative to grunt serve for previewing/DOM app development. it accesses localhost 8080 but I use this program called Mongoose b/c I couldn't get grunt serve to work a while back.

**Comment by jrhorn424** [comment]
We won't support other servers. There's no guarantee other tools are substitutable for our own. I suggest either not using the browser template, or not using your alternative server.

**Comment by logicmyth** [comment]
ok. will ditch mongoose. i feel i should inform this thread that the inspector on the page does not show scss attributes to the div i styled. is this a mongoose issue?
